### ISSUE TITLE
Text view needs to wrap text 

### ISSUE THREAD

**Issue by Rpoddar1953** [nv78/Anote-AbstractiveHealth#7]
When uploading a txt file, the preview window in the annotate tab has the text displayed in one line. It needs to wrap the text so that we can view the text scrolling vertically, not horizontally. See image below.
![image](https://github.com/nv78/Anote-AbstractiveHealth/assets/68236186/ef0a46cb-3fc4-4fa5-a8ba-223d2957e475)

**Comment by rajat10cube** [comment]
Made the changes, Please check (pull from main branch) and let me know if it works now as expected. Thanks
